defaults:
test:
  app:
    azureAccounts:
      taskclusterdev: "..."
  test:
    testBucket: "test-bucket-for-any-garbage"
  azure:
    accountId:  "taskclusterdev"
    accessKey:   "..."
  aws:
    accessKeyId:        "..."
    secretAccessKey:    "..."
  pulse:
    username:           "..."
    password:           "..."
