defaults:
  app:
    level: !env LEVEL
    # Publish references and schemas
    publishMetaData:  !env:bool PUBLISH_METADATA
  pulse:
    namespace: !env PULSE_NAMESPACE
    credentials:
      username: !env PULSE_USERNAME
      password: !env PULSE_PASSWORD
      hostname: !env PULSE_HOSTNAME
      vhost: !env PULSE_VHOST
    queueName: taskcluster-treeherder-dev
    prefetch: 40
  treeherder:
    routePrefix: !env TREEHERDER_ROUTE_PREFIX
  taskcluster:
    rootUrl: !env TASKCLUSTER_ROOT_URL
    credentials:
      clientId: !env TASKCLUSTER_CLIENT_ID
      accessToken: !env TASKCLUSTER_ACCESS_TOKEN
  aws:
    # Credentials with access to artifact buckets and
    # references/schemas.taskcluster.net if you wish to publish meta-data
    accessKeyId:      !env AWS_ACCESS_KEY_ID
    secretAccessKey:  !env AWS_SECRET_ACCESS_KEY
    region:           'us-west-2'
    apiVersion:       '2014-01-01'
  monitoring:
    project: !env MONITORING_PROJECT
    enable: !env:bool MONITORING_ENABLE

staging:
  pulse:
    queueName: taskcluster-treeherder-staging

production:
  pulse:
    queueName: taskcluster-treeherder
    namespace: taskcluster-treeherder
