$schema:            http://json-schema.org/draft-06/schema#
title:              ".taskcluster.yml format"
description: |
 Description of a taskcluster.yml file v1, which may be used to generate a taskgraph
 and tasks.
type:               object
properties:
  version:
    description:    Version of the format of this file; must be 1
    enum:           [1]
    type:           integer
  policy:
    pullRequests:
      description: |
          Policy for creating tasks for pull requests.  The effective policy is found in this property
          in the `.taskcluster.yml` file in the repository's default branch.  See the documentation for
          detailed definition of the options.
      type: string
      enum:
        - public
        - collaborators
  reporting:
    description: Policy for reporting status of PR or a commit. If absent, Github Statuses API is used
    type: string
    enum:
      - checks-v1
  tasks:
    title: Task definition template"
    description: |
      Definitions of tasks that can be scheduled. Rendered with JSON-e
    default: []
    oneOf:
      - type: array
        description: Each element of this should evaluate to a task definition via json-e
        items:
            type:               object
            additionalProperties: true
      - type: object
        description: This must evaluate to an array via json-e i.e. `$flatten`
        additionalProperties: true
additionalProperties: false
required:
  - version
