# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Maintain node dependencies for taskcluster
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    groups:
      # Groups together all minor/patch version updates for dependencies
      node-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Maintain node dependencies for @taskcluster/client
  - package-ecosystem: "npm"
    directory: "/clients/client"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    groups:
      # Groups together all minor/patch version updates for dependencies
      client-node-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Maintain node dependencies for @taskcluster/client-web
  - package-ecosystem: "npm"
    directory: "/clients/client-web"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    groups:
      # Groups together all minor/patch version updates for dependencies
      client-web-node-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Maintain cargo dependencies for taskcluster-client-rust
  - package-ecosystem: "cargo"
    directory: "/clients/client-rust"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    groups:
      # Groups together all minor/patch version updates for dependencies
      client-rust-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Maintain uv dependencies for taskcluster-client-python
  - package-ecosystem: "uv"
    directory: "/clients/client-py"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    groups:
      # Groups together all minor/patch version updates for dependencies
      client-python-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Maintain node dependencies for @taskcluster/ui
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    groups:
      # Groups together all minor/patch version updates for dependencies
      ui-node-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Maintain node dependencies for @taskcluster/ui e2e tests
  - package-ecosystem: "npm"
    directory: "/ui/test/e2e"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    groups:
      # Groups together all minor/patch version updates for dependencies
      e2e-ui-test-node-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Maintain go dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    groups:
      # Groups together all minor/patch version updates for dependencies
      go-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Set update schedule for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    groups:
      # Groups together all minor/patch version updates for dependencies
      gh-actions-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Maintain pip dependencies for taskgraph
  - package-ecosystem: "pip"
    directory: "/taskcluster"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    groups:
      # Groups together all minor/patch version updates for dependencies
      python-deps:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Ignore docker worker dependencies
  - package-ecosystem: "npm"
    directory: "/workers/docker-worker"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
    ignore:
      - dependency-name: "*"
