# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

  # Maintain node dependencies for taskcluster
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"

  # Maintain node dependencies for taskcluster-client
  - package-ecosystem: "npm"
    directory: "/clients/client"
    schedule:
      interval: "monthly"

  # Maintain node dependencies for taskcluster-client-web
  - package-ecosystem: "npm"
    directory: "/clients/client-web"
    schedule:
      interval: "monthly"

  # Maintain node dependencies for taskcluster-ui
  - package-ecosystem: "npm"
    directory: "/ui"
    schedule:
      interval: "monthly"

  # Maintain node dependencies for docker-worker
  - package-ecosystem: "npm"
    directory: "/workers/docker-worker"
    schedule:
      interval: "monthly"

  # Maintain go dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"

  # Set update schedule for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  # Maintain pip dependencies for taskgraph
  - package-ecosystem: "pip"
    directory: "/taskcluster"
    schedule:
      interval: "monthly"
