language: go
go:
  - 1.10

env:
  - "CGO_ENABLED=0 GIMME_OS=linux GIMME_ARCH=amd64"
  - "CGO_ENABLED=0 GIMME_OS=darwin GIMME_ARCH=amd64"
  - "CGO_ENABLED=0 GIMME_OS=windows GIMME_ARCH=amd64"
  - "CGO_ENABLED=0 GIMME_OS=windows GIMME_ARCH=386"

install:
  - "test $GIMME_OS.$GIMME_ARCH != linux.amd64 || go get github.com/mattn/goveralls github.com/taskcluster/livelog github.com/gordonklaus/ineffassign"

script:
  - "test $GIMME_OS.$GIMME_ARCH != linux.amd64 || go get ./gw-codegen"
  - "test $GIMME_OS.$GIMME_ARCH != linux.amd64 || go generate"
  - "test $GIMME_OS.$GIMME_ARCH != linux.amd64 || git status"
  - "test $GIMME_OS.$GIMME_ARCH != linux.amd64 || test $(git status --porcelain | wc -l) == 0"
  - "go get -ldflags \"-X main.revision=$(git rev-parse HEAD)\" -v -t ./..."
  - "test $GIMME_OS.$GIMME_ARCH != linux.amd64 || GORACE=history_size=7 travis_wait 30 ./gotestcover.sh coverage.report"
  - "test $GIMME_OS.$GIMME_ARCH != linux.amd64 || ${GOPATH}/bin/ineffassign ."

after_script:
  - "test $GIMME_OS.$GIMME_ARCH != linux.amd64 || ${GOPATH}/bin/goveralls -coverprofile=coverage.report -service=travis-ci"

before_deploy:
  - "source .travis_rename_releases.sh"

deploy:
  api_key:
    secure: KuifEWzfB5C9GFHMjFpSpbHWLN9cs/1afRuJhP4aADU3i55zb0QDzIu6+aGLlL0jsV5T07AqgPvJm4bOQNnWVhlhyHStrkIdzUpCtiCVNnPH3cYUkJ4/0zJyJaopnZfuX/2m2F+ajNC2Z94mxuu4qUUgqFO9x708xy0LYCofTEU=
  file:
    - "${RELEASE_FILE}"
  provider: releases
  skip_cleanup: true
  on:
    repo: taskcluster/generic-worker
    tags: true

notifications:
  irc:
    channels:
      - "irc.mozilla.org#taskcluster-bots"
    on_failure: always
    on_success: change
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Commit message : %{commit_message}"
