dist: trusty
language: node_js
cache: yarn
node_js:
- '10'
install:
- yarn install --frozen-lockfile
before_install:
- curl -sSfL https://yarnpkg.com/install.sh | bash # Required due to: https://github.com/travis-ci/travis-ci/issues/7951
- export PATH=$HOME/.yarn/bin:$PATH
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- yarn lint
- yarn test
