language: go

go:
  - 1.4

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/pierrre/gotestcover

script:
  - ${HOME}/gopath/bin/gotestcover -v -coverprofile=coverage.report ./...

after_script:
  - go tool cover -func=coverage.report
  - ${HOME}/gopath/bin/goveralls -coverprofile=coverage.report -service=travis-ci

# currently cannot customise per user fork, see:
# https://github.com/travis-ci/travis-ci/issues/1094
notifications:
  irc:
    channels:
      - "irc.mozilla.org#taskcluster-bots"
    on_success: always
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Commit message : %{commit_message}"
