language: python
python:
#  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "3.4"
  - "pypy"
#  - "pypy3"
# command to install dependencies
install:
  - "pip install nose rednose mock httmock"
  - "pip install ."
  - "python setup.py develop"
# command to run tests
script: nosetests
