[build]
  base    = "ui"
  command = "yarn build"
  publish = "ui/build"

[build.environment]
  YARN_FLAGS = "--frozen-lockfile"
  YARN_VERSION = "1.10.1"
  NODE_VERSION = "10.15.2"
  APPLICATION_NAME = "Taskcluster"
  GRAPHQL_ENDPOINT = "https://taskcluster-web-server.herokuapp.com/graphql"
  GRAPHQL_SUBSCRIPTION_ENDPOINT = "wss://taskcluster-web-server.herokuapp.com/subscription"
  LOGIN_STRATEGIES = ""
  TASKCLUSTER_ROOT_URL = "https://taskcluster.net"

# Rule for Single Page Applications (docs)
[[redirects]]
  from = "/docs/*"
  to = "/docs.html"
  status = 200

# Rule for Single Page Applications (app)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
