[build]
  base    = "ui"
  command = "GENERATE_ENV_JS=1 yarn build"
  publish = "build"
  # an exit-code of 1 indicates the contents have changed
  # netlify build will be skipped if the exit-code is 0
  # command will be run from the base directory (i.e., ui)
  ignore = "git diff --quiet HEAD^ HEAD -- . ':!docs'"

[build.environment]
  YARN_FLAGS = "--immutable"
  NODE_VERSION = "18.18.1"
  APPLICATION_NAME = "Taskcluster"
  GRAPHQL_ENDPOINT = "https://community-tc.services.mozilla.com/graphql"
  GRAPHQL_SUBSCRIPTION_ENDPOINT = "https://community-tc.services.mozilla.com/subscription"
  UI_LOGIN_STRATEGY_NAMES = ""
  TASKCLUSTER_ROOT_URL = "https://community-tc.services.mozilla.com"

# Rule for Single Page Applications (docs)
[[redirects]]
  from = "/docs/*"
  to = "/docs.html"
  status = 200

# Netlify is only used for docs.taskcluster.net
# so always (force) a redirect to /docs so we don't
# use the index page intended for the app as landing
[[redirects]]
  from = "/"
  to = "/docs/"
  status = 301
  force = true
