kind: Service
apiVersion: v1
metadata:
  name: ${projectName}
  labels: {$eval: labels}
spec:
  type: NodePort
  selector: {$eval: labels}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
