---
trust-domain: taskcluster
task-priority: highest

taskgraph:
  register: src:register
  repositories:
    taskcluster:
      name: taskcluster

workers:
  aliases:
    ci:
      provisioner: proj-taskcluster
      os: linux
      implementation: docker-worker
      worker-type: ci
    dw-ci:
      provisioner: proj-taskcluster
      os: linux
      implementation: docker-worker
      worker-type: dw-ci
    release:
      provisioner: proj-taskcluster
      os: linux
      implementation: generic-worker
      worker-type: release
    gw-ci-windows2012r2-amd64:
      provisioner: proj-taskcluster
      os: windows
      implementation: generic-worker
      worker-type: gw-ci-windows2012r2-amd64
