defaults:
  taskcluster:
    rootUrl:        !env TASKCLUSTER_ROOT_URL
    credentials:
      clientId:     !env TASKCLUSTER_CLIENT_ID
      accessToken:  !env TASKCLUSTER_ACCESS_TOKEN

  server:
    port:           !env:number PORT
    env:            'development'
    forceSSL:       !env:bool FORCE_SSL
    trustProxy:     !env:bool TRUST_PROXY


  monitor:
    mock:           true
    enable:         !env:bool MONITORING_ENABLE

  pulse:
    username:       !env PULSE_USERNAME
    password:       !env PULSE_PASSWORD
    hostname:       !env PULSE_HOSTNAME
    vhost:          !env PULSE_VHOST

  app:
    publishMetaData: !env:bool PUBLISH_METADATA


production:
  server:
    env:            production

  monitor:
    mock:           false

test:
  monitor:
    enable:         false

  server:
    port:           12345
