defaults:
  taskcluster:
      rootUrl: ...
  pulse:
    namespace:
    username: ..
    password: ..
    hostname: ..
    vhost: ..
  login:
    strategies:
      github:
        clientId: ...
        clientSecret: ...
