project_name: "taskcluster-built-in-workers"
secrets:
  taskcluster_client_id: "static/taskcluster/built-in-workers"
  taskcluster_access_token: ".Values.builtInWorkersAccessToken"
  node_env: "production"
  monitoring_enable: "true"
  publish_metadata: "false"
deployments:
  - service_name: "built-in-workers"
    proc_name: "server"
    root_url: ".Values.rootUrl"
    docker_image: ".Values.dockerImage"
    background_job: true
