project_name: "taskcluster-github"
secrets:
  azure_account: ".Values.tfAzureAccount"
  force_ssl: "false"
  github_app_id: ".Values.githubAppId" 
  github_private_pem: ".Values.githubPrivatePem"
  monitoring_enable: "true"
  node_env: "production"
  publish_metadata: "false"
  pulse_hostname: ".Values.tfRabbitmqHostname"
  pulse_password: ".Values.githubPulsePassword"
  pulse_username: ".Values.githubPulseUsername"
  pulse_vhost: ".Values.pulseVhost"
  taskcluster_access_token: ".Values.githubAccessToken"
  taskcluster_client_id: "static/taskcluster/github"
  trust_proxy: "true"
  webhook_secret: ".Values.githubWebhookSecret"
deployments:
  - service_name: "github"
    docker_image: ".Values.dockerImage"
    proc_name: "web"
    readiness_path: "/api/github/v1/ping"
    root_url: ".Values.rootUrl"
  - service_name: "github"
    background_job: true
    docker_image: ".Values.dockerImage"
    proc_name: "worker"
    root_url: ".Values.rootUrl"
cronjobs:
  - service_name: "github"
    deadline_seconds: 86400
    docker_image: ".Values.dockerImage"
    job_name: "sync"
    root_url: ".Values.rootUrl"
    schedule: "0 0 * * *"
