project_name: "taskcluster-index"
secrets:
  azure_account: ".Values.tfAzureAccount"
  force_ssl: "false"
  node_env: "production"
  pulse_hostname: ".Values.tfRabbitmqHostname"
  pulse_password: ".Values.indexPulsePassword"
  pulse_username: ".Values.indexPulseUsername"
  pulse_vhost: ".Values.pulseVhost"
  taskcluster_access_token: ".Values.indexAccessToken"
  taskcluster_client_id: "static/taskcluster/index"
  trust_proxy: "true"
deployments:
  - service_name: "index"
    docker_image: ".Values.dockerImage"
    proc_name: "web"
    readiness_path: "/api/index/v1/ping"
    root_url: ".Values.rootUrl"
  - service_name: "index"
    docker_image: ".Values.dockerImage"
    proc_name: "handlers"
    root_url: ".Values.rootUrl"
cronjobs:
  - service_name: "index"
    deadline_seconds: 86400
    docker_image: ".Values.dockerImage"
    job_name: "expire"
    project_name: "taskcluster-index"
    root_url: ".Values.rootUrl"
    schedule: "0 0 * * *"
