project_name: "taskcluster-web-server"
secrets:
  login_strategies: ".Values.loginStrategies" 
  monitoring_enable: "true"
  monitoring_project: "taskcluster-web-server"
  node_env: "production"
  public_url: ".Values.rootUrl"
  pulse_hostname: ".Values.tfRabbitmqHostname"
  pulse_password: ".Values.webServerPulsePassword"
  pulse_username: ".Values.webServerPulseUsername"
  pulse_vhost: ".Values.pulseVhost"
  taskcluster_access_token: ".Values.webServerAccessToken"
  taskcluster_client_id: "static/taskcluster/web-server"
deployments:
  - service_name: "web-server"
    docker_image: ".Values.dockerImage"
    proc_name: "web"
    readiness_path: "/.well-known/apollo/server-health"
    root_url: ".Values.rootUrl"
