---
defaults:
  azure:
    account: "..."
  taskcluster:
    credentials:
      clientId: "..."
      accessToken: "..."
verify:
  taskcluster:
    # These credentials must have the scopes:
    # * 'purge-cache:verifyprovisioner/verifyworker:verifycache'
    credentials:
      clientId: "..."
      accessToken: "..."
