apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskcluster-references-web
  labels: &ref_0
    app.kubernetes.io/name: taskcluster-references
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-references-web
    app.kubernetes.io/part-of: taskcluster
spec:
  {{- if not .Values.references.autoscaling.enabled }}
  replicas: {{ int (.Values.references.procs.web.replicas) }}
  {{- end }}
  selector:
    matchLabels: *ref_0
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-references-secret.yaml") . | sha256sum }}'
      labels: *ref_0
    spec:
      serviceAccountName: taskcluster-references
      imagePullSecrets: {{ if .Values.imagePullSecret }}{{ toJson (list (dict "name" .Values.imagePullSecret)) }}{{ else }}[]{{ end }}
      terminationGracePeriodSeconds: 210
      securityContext:
        runAsNonRoot: true
      containers:
        - name: taskcluster-references-web
          image: '{{ .Values.dockerImage }}'
          imagePullPolicy: Always
          args:
            - references/web
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: '{{ .Values.references.procs.web.cpu }}'
              memory: '{{ .Values.references.procs.web.memory }}'
          env:
            - name: PORT
              value: '80'
            - name: TASKCLUSTER_ROOT_URL
              value: '{{ .Values.rootUrl }}'
            - name: USE_KUBERNETES_DNS_SERVICE_DISCOVERY
              value: '{{ .Values.useKubernetesDnsServiceDiscovery }}'
            - name: NODE_ENV
              value: production
          envFrom:
            - secretRef:
                name: taskcluster-references
            - configMapRef:
                name: taskcluster-references
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /references/
              port: 80
            timeoutSeconds: 5
            periodSeconds: 10
            initialDelaySeconds: 6
          livenessProbe:
            httpGet:
              path: /references/
              port: 80
            timeoutSeconds: 3
            initialDelaySeconds: 15
            periodSeconds: 30
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - '-c'
                  - sleep 120
