{{- if .Values.ui.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: taskcluster-ui-hpa
  labels:
    app.kubernetes.io/name: taskcluster-ui
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-ui-web
    app.kubernetes.io/part-of: taskcluster
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: taskcluster-ui
  minReplicas: '{{ .Values.ui.autoscaling.minReplicas }}'
  maxReplicas: '{{ .Values.ui.autoscaling.maxReplicas }}'
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: '{{ .Values.ui.autoscaling.targetCPUUtilizationPercentage }}'
    {{- if .Values.ui.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.ui.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
