apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: taskcluster-treeherder
data:
  PULSE_NAMESPACE: '{{ .Values.treeherder.pulse_namespace | toJson | trimAll "\"" | b64enc }}'
  PULSE_USERNAME: '{{ .Values.treeherder.pulse_username | toJson | trimAll "\"" | b64enc }}'
  PULSE_PASSWORD: '{{ .Values.treeherder.pulse_password | toJson | trimAll "\"" | b64enc }}'
  PULSE_HOSTNAME: '{{ .Values.treeherder.pulse_hostname | toJson | trimAll "\"" | b64enc }}'
  PULSE_VHOST: '{{ .Values.treeherder.pulse_vhost | toJson | trimAll "\"" | b64enc }}'
  TREEHERDER_ROUTE_PREFIX: '{{ .Values.treeherder.treeherder_route_prefix | toJson | trimAll "\"" | b64enc }}'
  TASKCLUSTER_ROOT_URL: '{{ .Values.treeherder.taskcluster_root_url | toJson | trimAll "\"" | b64enc }}'
  TASKCLUSTER_CLIENT_ID: '{{ .Values.treeherder.taskcluster_client_id | toJson | trimAll "\"" | b64enc }}'
  TASKCLUSTER_ACCESS_TOKEN: '{{ .Values.treeherder.taskcluster_access_token | toJson | trimAll "\"" | b64enc }}'
  AWS_ACCESS_KEY_ID: '{{ .Values.treeherder.aws_access_key_id | toJson | trimAll "\"" | b64enc }}'
  AWS_SECRET_ACCESS_KEY: '{{ .Values.treeherder.aws_secret_access_key | toJson | trimAll "\"" | b64enc }}'
  LEVEL: '{{ .Values.treeherder.level | toJson | trimAll "\"" | b64enc }}'
