apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskcluster-worker-manager-workerscanner
  labels:
    app.kubernetes.io/name: taskcluster-taskcluster-worker-manager
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: worker-manager-workerscanner
    app.kubernetes.io/part-of: taskcluster
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: taskcluster-worker-manager
      app.kubernetes.io/instance: '{{ .Release.Name }}'
      app.kubernetes.io/component: worker-manager-workerscanner
      app.kubernetes.io/part-of: taskcluster
      app.kubernetes.io/managed-by: helm
  replicas: {{ int (.Values.worker_manager.procs.workerscanner.replicas) }}
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-worker-manager-secret.yaml") . | sha256sum }}'
      labels:
        app.kubernetes.io/name: taskcluster-worker-manager
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/component: worker-manager-workerscanner
        app.kubernetes.io/part-of: taskcluster
        app.kubernetes.io/managed-by: helm
    spec:
      serviceAccountName: taskcluster-worker-manager
      containers:
        - name: taskcluster-worker-manager
          image: '{{ .Values.dockerImage }}'
          imagePullPolicy: Always
          args:
            - worker-manager/workerscanner
          resources:
            requests:
              cpu: '{{ .Values.worker_manager.procs.workerscanner.cpu }}'
              memory: '{{ .Values.worker_manager.procs.workerscanner.memory }}'
          env:
            - name: TASKCLUSTER_ROOT_URL
              value: '{{ .Values.rootUrl }}'
          envFrom:
            - secretRef:
                name: taskcluster-worker-manager
          ports: []
