apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskcluster-auth-web
  labels:
    app.kubernetes.io/name: taskcluster-taskcluster-auth
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: auth-web
    app.kubernetes.io/part-of: taskcluster
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: taskcluster-auth
      app.kubernetes.io/instance: '{{ .Release.Name }}'
      app.kubernetes.io/component: auth-web
      app.kubernetes.io/part-of: taskcluster
      app.kubernetes.io/managed-by: helm
  replicas: {{ int (.Values.auth.procs.web.replicas) }}
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-auth-secret.yaml") . | sha256sum }}'
      labels:
        app.kubernetes.io/name: taskcluster-auth
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/component: auth-web
        app.kubernetes.io/part-of: taskcluster
        app.kubernetes.io/managed-by: helm
    spec:
      serviceAccountName: taskcluster-auth
      containers:
        - name: taskcluster-auth
          image: '{{ .Values.dockerImage }}'
          imagePullPolicy: Always
          args:
            - auth/web
          resources:
            requests:
              cpu: '{{ .Values.auth.procs.web.cpu }}'
              memory: '{{ .Values.auth.procs.web.memory }}'
          env:
            - name: PORT
              value: '80'
            - name: TASKCLUSTER_ROOT_URL
              value: '{{ .Values.rootUrl }}'
          envFrom:
            - secretRef:
                name: taskcluster-auth
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /api/auth/v1/ping
              port: 80
            timeoutSeconds: 5
            periodSeconds: 10
            initialDelaySeconds: 3
