apiVersion: batch/v1
kind: CronJob
metadata:
  name: taskcluster-secrets-expire
  labels: &ref_0
    app.kubernetes.io/name: taskcluster-secrets
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-secrets-expire
    app.kubernetes.io/part-of: taskcluster
spec:
  concurrencyPolicy: Forbid
  schedule: 0 * * * *
  jobTemplate:
    metadata:
      labels: *ref_0
    spec:
      activeDeadlineSeconds: 540
      template:
        metadata:
          labels: *ref_0
        spec:
          restartPolicy: OnFailure
          imagePullSecrets: {{ if .Values.imagePullSecret }}{{ toJson (list (dict "name" .Values.imagePullSecret)) }}{{ else }}[]{{ end }}
          securityContext:
            runAsNonRoot: true
          containers:
            - name: taskcluster-secrets-expire
              image: '{{ .Values.dockerImage }}'
              imagePullPolicy: Always
              args:
                - secrets/expire
              securityContext:
                allowPrivilegeEscalation: false
              resources:
                requests:
                  cpu: '{{ .Values.secrets.procs.expire.cpu }}'
                  memory: '{{ .Values.secrets.procs.expire.memory }}'
              env:
                - name: TASKCLUSTER_ROOT_URL
                  value: '{{ .Values.rootUrl }}'
                - name: USE_KUBERNETES_DNS_SERVICE_DISCOVERY
                  value: '{{ .Values.useKubernetesDnsServiceDiscovery }}'
                - name: NODE_ENV
                  value: production
              envFrom:
                - secretRef:
                    name: taskcluster-secrets
                - configMapRef:
                    name: taskcluster-secrets
