apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskcluster-references-web
  labels:
    app.kubernetes.io/name: taskcluster-taskcluster-references
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: references-web
    app.kubernetes.io/part-of: taskcluster
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: taskcluster-references
      app.kubernetes.io/instance: '{{ .Release.Name }}'
      app.kubernetes.io/component: references-web
      app.kubernetes.io/part-of: taskcluster
      app.kubernetes.io/managed-by: helm
  replicas: {{ int (.Values.references.procs.web.replicas) }}
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-references-secret.yaml") . | sha256sum }}'
      labels:
        app.kubernetes.io/name: taskcluster-references
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/component: references-web
        app.kubernetes.io/part-of: taskcluster
        app.kubernetes.io/managed-by: helm
    spec:
      serviceAccountName: taskcluster-references
      containers:
        - name: taskcluster-references
          image: '{{ .Values.dockerImage }}'
          imagePullPolicy: Always
          args:
            - references/web
          resources:
            requests:
              cpu: '{{ .Values.references.procs.web.cpu }}'
              memory: '{{ .Values.references.procs.web.memory }}'
          env:
            - name: PORT
              value: '80'
            - name: TASKCLUSTER_ROOT_URL
              value: '{{ .Values.rootUrl }}'
          envFrom:
            - secretRef:
                name: taskcluster-references
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /references/
              port: 80
            timeoutSeconds: 5
            periodSeconds: 10
            initialDelaySeconds: 3
