apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: taskcluster-secrets-expire
  labels:
    app.kubernetes.io/name: taskcluster-secrets
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-secrets-expire
    app.kubernetes.io/part-of: taskcluster
    app.kubernetes.io/managed-by: helm
spec:
  schedule: 0 * * * *
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: taskcluster-secrets
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/component: taskcluster-secrets-expire
        app.kubernetes.io/part-of: taskcluster
        app.kubernetes.io/managed-by: helm
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: taskcluster-secrets
            app.kubernetes.io/instance: '{{ .Release.Name }}'
            app.kubernetes.io/component: taskcluster-secrets-expire
            app.kubernetes.io/part-of: taskcluster
            app.kubernetes.io/managed-by: helm
        spec:
          restartPolicy: OnFailure
          activeDeadlineSeconds: 600
          containers:
            - name: taskcluster-secrets-expire
              image: '{{ .Values.dockerImage }}'
              imagePullPolicy: Always
              args:
                - secrets/expire
              resources:
                requests:
                  cpu: '{{ .Values.secrets.procs.expire.cpu }}'
                  memory: '{{ .Values.secrets.procs.expire.memory }}'
              env:
                - name: TASKCLUSTER_ROOT_URL
                  value: '{{ .Values.rootUrl }}'
              envFrom:
                - secretRef:
                    name: taskcluster-secrets
