apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskcluster-object-web
  labels: &ref_0
    app.kubernetes.io/name: taskcluster-object
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-object-web
    app.kubernetes.io/part-of: taskcluster
spec:
  replicas: {{ int (.Values.object.procs.web.replicas) }}
  selector:
    matchLabels: *ref_0
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-object-secret.yaml") . | sha256sum }}'
      labels: *ref_0
    spec:
      serviceAccountName: taskcluster-object
      containers:
        - name: taskcluster-object-web
          image: '{{ .Values.dockerImage }}'
          imagePullPolicy: Always
          args:
            - object/web
          resources:
            requests:
              cpu: '{{ .Values.object.procs.web.cpu }}'
              memory: '{{ .Values.object.procs.web.memory }}'
          env:
            - name: PORT
              value: '80'
            - name: TASKCLUSTER_ROOT_URL
              value: '{{ .Values.rootUrl }}'
            - name: USE_KUBERNETES_DNS_SERVICE_DISCOVERY
              value: '{{ .Values.useKubernetesDnsServiceDiscovery }}'
            - name: NODE_ENV
              value: production
          envFrom:
            - secretRef:
                name: taskcluster-object
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /api/object/v1/ping
              port: 80
            timeoutSeconds: 5
            periodSeconds: 10
            initialDelaySeconds: 3
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - '-c'
                - exit $(awk 'BEGIN{srand(); print (rand() > 0.3)}')
            initialDelaySeconds: 86400
            periodSeconds: 60
            failureThreshold: 1
