apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskcluster-hooks-scheduler
  labels:
    app.kubernetes.io/name: taskcluster-hooks
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/component: taskcluster-hooks-scheduler
    app.kubernetes.io/part-of: taskcluster
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: taskcluster-hooks
      app.kubernetes.io/instance: '{{ .Release.Name }}'
      app.kubernetes.io/component: taskcluster-hooks-scheduler
      app.kubernetes.io/part-of: taskcluster
      app.kubernetes.io/managed-by: helm
  replicas: {{ int (.Values.hooks.procs.scheduler.replicas) }}
  template:
    metadata:
      annotations:
        checksum/secret: '{{ include (print $.Template.BasePath "/taskcluster-hooks-secret.yaml") . | sha256sum }}'
      labels:
        app.kubernetes.io/name: taskcluster-hooks
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/component: taskcluster-hooks-scheduler
        app.kubernetes.io/part-of: taskcluster
        app.kubernetes.io/managed-by: helm
    spec:
      serviceAccountName: taskcluster-hooks
      containers:
        - name: taskcluster-hooks
          image: '{{ .Values.dockerImage }}'
          imagePullPolicy: Always
          args:
            - hooks/scheduler
          resources:
            requests:
              cpu: '{{ .Values.hooks.procs.scheduler.cpu }}'
              memory: '{{ .Values.hooks.procs.scheduler.memory }}'
          env:
            - name: TASKCLUSTER_ROOT_URL
              value: '{{ .Values.rootUrl }}'
          envFrom:
            - secretRef:
                name: taskcluster-hooks
          ports: []
