apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: taskcluster-notify-secrets-read
rules:
- apiGroups:
  - ''
  resources:
  - secrets/taskcluster-notify
  verbs:
  - get
  - watch
  - list
