applicationName: My Taskcluster
rootUrl: ...
dockerImage: ...
ingressStaticIpName: ...
ingressCertName: ...
pulseHostname: ...
pulseVhost: ...
azureAccountId: ...
forceSSL: false
trustProxy: true
nodeEnv: production
meta: {}
errorConfig: {}
auth:
  static_clients:
    - clientId: static/taskcluster/built-in-workers
      accessToken: ...
    - clientId: static/taskcluster/github
      accessToken: ...
    - clientId: static/taskcluster/hooks
      accessToken: ...
    - clientId: static/taskcluster/index
      accessToken: ...
    - clientId: static/taskcluster/notify
      accessToken: ...
    - clientId: static/taskcluster/purge-cache
      accessToken: ...
    - clientId: static/taskcluster/queue
      accessToken: ...
    - clientId: static/taskcluster/secrets
      accessToken: ...
    - clientId: static/taskcluster/web-server
      accessToken: ...
    - clientId: static/taskcluster/worker-manager
      accessToken: ...
    - clientId: static/taskcluster/root
      accessToken: ...
  azure_accounts: {}
  sentry_organization: ...
  sentry_host: ...
  sentry_auth_token: ...
  sentry_team: ...
  sentry_key_prefix: ...
  websocktunnel_secret: ...
  docs_bucket: ...
  schemas_bucket: ...
  refs_bucket: ...
  audit_log: ...
  azure_account_key: ...
  azure_signing_key: ...
  azure_crypto_key: ...
  pulse_username: ...
  pulse_password: ...
  aws_credentials_allowed_buckets: {}
  gcp_credentials_allowed_projects: {}
built_in_workers:
  taskcluster_access_token: ...
github:
  bot_username: ...
  taskcluster_access_token: ...
  github_private_pem: ...
  github_app_id: ...
  webhook_secret: []
  provisioner_id: ...
  worker_type: ...
  pulse_username: ...
  pulse_password: ...
hooks:
  influx_connection: ...
  azure_signing_key: ...
  azure_crypto_key: ...
  taskcluster_access_token: ...
  pulse_username: ...
  pulse_password: ...
index:
  taskcluster_access_token: ...
  pulse_username: ...
  pulse_password: ...
notify:
  email_source_address: ...
  email_blacklist: {}
  taskcluster_access_token: ...
  aws_access_key_id: ...
  aws_secret_access_key: ...
  aws_region: ...
  pulse_username: ...
  pulse_password: ...
  irc_server: ...
  irc_nick: ...
  irc_user_name: ...
  irc_real_name: ...
  irc_password: ...
  irc_port: ...
  irc_debug: ...
purge_cache:
  taskcluster_access_token: ...
queue:
  public_artifact_bucket: ...
  private_artifact_bucket: ...
  azure_report_chance: ...
  azure_report_threshold: ...
  public_artifact_ec2_proxies: {}
  public_artifact_bucket_cdn: ...
  use_cloud_mirror: true/false
  task_cache_max_size: ...
  taskcluster_access_token: ...
  azure_account_key: ...
  pulse_username: ...
  pulse_password: ...
  aws_access_key_id: ...
  aws_secret_access_key: ...
  artifact_region: ...
secrets:
  taskcluster_access_token: ...
  azure_crypto_key: ...
  azure_signing_key: ...
web_server:
  public_url: ...
  additional_allowed_cors_origin: ...
  taskcluster_access_token: ...
  azure_signing_key: ...
  azure_crypto_key: ...
  pulse_username: ...
  pulse_password: ...
  registered_clients: {}
  ui_login_strategies: {}
  session_secret: ...
worker_manager:
  provisioner_iterate_config: {}
  worker_scanner_iterate_config: {}
  taskcluster_access_token: ...
  pulse_username: ...
  pulse_password: ...
  providers: {}
ui:
  graphql_subscription_endpoint: ...
  graphql_endpoint: ...
  ui_login_strategy_names: ...
  banner_message: ...
references: {}
