applicationName: My Taskcluster
rootUrl: ...
dockerImage: ...
ingressStaticIpName: ...
ingressCertName: ...
pulseHostname: ...
pulseAmqps: true
pulseVhost: ...
forceSSL: false
trustProxy: true
nodeEnv: production
meta: {}
auth:
  static_clients:
    - clientId: static/taskcluster/built-in-workers
      accessToken: ...
    - clientId: static/taskcluster/github
      accessToken: ...
    - clientId: static/taskcluster/hooks
      accessToken: ...
    - clientId: static/taskcluster/index
      accessToken: ...
    - clientId: static/taskcluster/notify
      accessToken: ...
    - clientId: static/taskcluster/object
      accessToken: ...
    - clientId: static/taskcluster/purge-cache
      accessToken: ...
    - clientId: static/taskcluster/queue
      accessToken: ...
    - clientId: static/taskcluster/secrets
      accessToken: ...
    - clientId: static/taskcluster/web-server
      accessToken: ...
    - clientId: static/taskcluster/worker-manager
      accessToken: ...
    - clientId: static/taskcluster/root
      accessToken: ...
  sentry_organization: ...
  sentry_host: ...
  sentry_auth_token: ...
  sentry_team: ...
  sentry_key_prefix: ...
  websocktunnel_secret: ...
  docs_bucket: ...
  schemas_bucket: ...
  refs_bucket: ...
  audit_log: ...
  azure_crypto_key: ...
  read_db_url: ...
  write_db_url: ...
  db_crypto_keys: {}
  pulse_username: ...
  pulse_password: ...
  azure_accounts: {}
  aws_credentials_allowed_buckets: {}
  gcp_credentials_allowed_projects: {}
  procs:
    web:
      cpu: 10m
    purgeExpiredClients:
      cpu: 10m
built_in_workers:
  taskcluster_access_token: ...
  procs:
    server:
      cpu: 10m
github:
  bot_username: ...
  taskcluster_access_token: ...
  github_private_pem: ...
  github_app_id: ...
  webhook_secret: ''
  provisioner_id: ...
  worker_type: ...
  read_db_url: ...
  write_db_url: ...
  pulse_username: ...
  pulse_password: ...
  procs:
    web:
      cpu: 10m
    worker:
      cpu: 10m
    sync:
      cpu: 10m
hooks:
  influx_connection: ...
  azure_crypto_key: ...
  read_db_url: ...
  write_db_url: ...
  db_crypto_keys: {}
  taskcluster_access_token: ...
  pulse_username: ...
  pulse_password: ...
  procs:
    web:
      cpu: 10m
    scheduler:
      cpu: 10m
    listeners:
      cpu: 10m
    expires:
      cpu: 10m
index:
  read_db_url: ...
  write_db_url: ...
  taskcluster_access_token: ...
  pulse_username: ...
  pulse_password: ...
  procs:
    web:
      cpu: 10m
    handlers:
      cpu: 10m
    expire:
      cpu: 10m
notify:
  email_source_address: ...
  email_blacklist: {}
  taskcluster_access_token: ...
  read_db_url: ...
  write_db_url: ...
  aws_access_key_id: ...
  aws_secret_access_key: ...
  aws_region: ...
  pulse_username: ...
  pulse_password: ...
  matrix_base_url: ...
  matrix_access_token: ...
  matrix_user_id: ...
  slack_api_url: ...
  slack_access_token: ...
  procs:
    web:
      cpu: 10m
    handler:
      cpu: 10m
object:
  backends: {}
  backend_map: {}
  middleware: {}
  taskcluster_access_token: ...
  read_db_url: ...
  write_db_url: ...
  db_crypto_keys: {}
  procs:
    web:
      cpu: 10m
    expire:
      cpu: 10m
purge_cache:
  read_db_url: ...
  write_db_url: ...
  taskcluster_access_token: ...
  procs:
    web:
      cpu: 10m
    expireCachePurges:
      cpu: 10m
queue:
  task_claim_timeout: ...
  public_artifact_bucket: ...
  private_artifact_bucket: ...
  sign_public_artifact_urls: true/false
  public_artifact_bucket_cdn: ...
  task_cache_max_size: ...
  taskcluster_access_token: ...
  read_db_url: ...
  write_db_url: ...
  pulse_username: ...
  pulse_password: ...
  aws_access_key_id: ...
  aws_secret_access_key: ...
  artifact_region: ...
  procs:
    web:
      cpu: 10m
    claimResolver:
      cpu: 10m
    deadlineResolver:
      cpu: 10m
    dependencyResolver:
      cpu: 10m
    expireArtifacts:
      cpu: 10m
    expireTask:
      cpu: 10m
    expireTaskGroups:
      cpu: 10m
    expireTaskDependency:
      cpu: 10m
    expireQueueMessages:
      cpu: 10m
    expireWorkerInfo:
      cpu: 10m
secrets:
  taskcluster_access_token: ...
  azure_crypto_key: ...
  read_db_url: ...
  write_db_url: ...
  db_crypto_keys: {}
  procs:
    web:
      cpu: 10m
    expire:
      cpu: 10m
web_server:
  public_url: ...
  additional_allowed_cors_origin: ...
  taskcluster_access_token: ...
  azure_crypto_key: ...
  read_db_url: ...
  write_db_url: ...
  db_crypto_keys: {}
  pulse_username: ...
  pulse_password: ...
  registered_clients: []
  ui_login_strategies: {}
  session_secret: ...
  procs:
    web:
      cpu: 10m
    scanner:
      cpu: 10m
    cleanup_expire_auth_codes:
      cpu: 10m
    cleanup_expire_access_tokens:
      cpu: 10m
worker_manager:
  provisioner_iterate_config: {}
  worker_scanner_iterate_config: {}
  taskcluster_access_token: ...
  read_db_url: ...
  write_db_url: ...
  db_crypto_keys: {}
  pulse_username: ...
  pulse_password: ...
  providers: {}
  procs:
    web:
      cpu: 10m
    provisioner:
      cpu: 10m
    workerscanner:
      cpu: 10m
    expire_workers:
      cpu: 10m
    expire_worker_pools:
      cpu: 10m
    expire_errors:
      cpu: 10m
ui:
  graphql_subscription_endpoint: ...
  graphql_endpoint: ...
  ui_login_strategy_names: ...
  banner_message: ...
  site_specific: {}
  procs:
    web:
      cpu: 10m
references:
  procs:
    web:
      cpu: 10m
