[package]
name = "taskcluster-upload"
version = "44.4.0"
authors = ["Dustin J. Mitchell <dustin@mozilla.com>"]
edition = "2018"
license = "MPL-2.0"
description = "Taskcluster Upload Support"
repository = "https://github.com/taskcluster/taskcluster"

[dependencies]
taskcluster = { version = "44.4.0", path = "../client" }
anyhow = "1.0"
async-trait = "0.1"
reqwest = { version = "0.11", features = ["json", "stream"] }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
tokio = { version = "1.2", features = ["macros", "time", "fs"] }
tokio-util = { version = "0.6", features = ["codec", "io"] }
slugid = "1.0.0"
base64 = "0.12.0"
sha2 = "0.9"

[dev-dependencies]
httptest = "0.15.3"
tempfile = "3"
ring = "0.16"
